version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dialer
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build: ./backend
    command: npm run dev
    environment:
      - PORT=4000
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/dialer
      - REDIS_URL=redis://redis:6379
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - JWT_SECRET=dev
      - REFRESH_SECRET=dev
      - DNCR_BASE_URL=${DNCR_BASE_URL}
      - DNCR_BEARER=${DNCR_BEARER}
      - THREECX_BASE_URL=${THREECX_BASE_URL}
      - THREECX_API_ID=${THREECX_API_ID}
      - THREECX_API_KEY=${THREECX_API_KEY}
      - THREECX_QUEUE_DEFAULT=800
      - DEFAULT_ALLOWED_CLIS=${DEFAULT_ALLOWED_CLIS}
      - THREECX_WEBHOOK_SECRET=${THREECX_WEBHOOK_SECRET}
      - S3_AUDIT_BUCKET=${S3_AUDIT_BUCKET}
      - S3_REGION=${S3_REGION}
      - KMS_KEY_ALIAS=${KMS_KEY_ALIAS}
      - S3_BACKUP_BUCKET=${S3_BACKUP_BUCKET}
      - BUSINESS_HOURS_TZ=Asia/Dubai
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_NAME=${MAIL_NAME}
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
  frontend:
    build: ./frontend
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend
  worker:
    build: ./worker
    command: npm run dev
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/dialer
      - REDIS_URL=redis://redis:6379
      - S3_AUDIT_BUCKET=${S3_AUDIT_BUCKET}
      - S3_REGION=${S3_REGION}
      - KMS_KEY_ALIAS=${KMS_KEY_ALIAS}
      - S3_BACKUP_BUCKET=${S3_BACKUP_BUCKET}
      - DNCR_BASE_URL=${DNCR_BASE_URL}
      - DNCR_BEARER=${DNCR_BEARER}
      - THREECX_BASE_URL=${THREECX_BASE_URL}
      - THREECX_API_ID=${THREECX_API_ID}
      - THREECX_API_KEY=${THREECX_API_KEY}
      - THREECX_QUEUE_DEFAULT=800
      - DEFAULT_ALLOWED_CLIS=${DEFAULT_ALLOWED_CLIS}
      - BUSINESS_HOURS_TZ=Asia/Dubai
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_NAME=${MAIL_NAME}
    depends_on:
      - postgres
      - redis
volumes:
  pgdata: